Improve primary client
UniversalRobots/Universal_Robots_Client_Library pull request #137
Opened 2022-12-28 14:39 UTC by urmarp

Improved primary interface, this includes following changes:

 * Added message handlers for messages received through primary client

 * Changed primary pipeline and full driver example

 * Added datatype: vector6f_t and vector6uin8_t

 * Added parsing of vector6f_t

 * Changed timeout in producer

 * Added parsing of more messages from primary interface

 * Added calibration check in constructor of primary client

 * Added calibration checksum to urdriver constructor

 * Added test for primary client and primary parser

 * Added funtionality to set robot as simulated or real

 * Added wait in full driver example

2023-01-05 10:54 UTC, fmauch commented
@urmarp this would be easier to review if these were multiple commits.

2023-01-05 11:09 UTC, fmauch requested changes
Before reviewing this any further: Could you please elaborate what you have done? What is the handler concept and why did you add this?

Again, splitting this into multiple commits (maybe with commit messages going into more detail) might make things a lot clearer.

2023-01-05 11:09 UTC, fmauch commented on include/ur_client_library/comm/producer.h
> -
Why exactly did you drop this? I don't remember out of my head why we have it there, but I would be hesitant deleting this without further information.

2023-01-06 08:33 UTC, urmarp commented
> Before reviewing this any further: Could you please elaborate what you have done? What is the handler concept and why did you add this?
> 
> Again, splitting this into multiple commits (maybe with commit messages going into more detail) might make things a lot clearer.

I have split the commit into multiple commits and tried to explain the thoughts behind the changes. 

Added message handlers for the messages from the primary interface. These handlers save the data from the latest message of each type, which can then be accessed through the primary client. The handlers also enable the possibility to handle the data differently for each message. The primary client can through its consumer get the message handlers and from the message handlers get the latest message of each type.

2024-05-28 09:49 UTC, fmauch commented
Closing this in favor of #186

2024-05-28 09:49 UTC, closed without merging