Add support for setting socket max num tries and reconnect timeout
UniversalRobots/Universal_Robots_Client_Library pull request #141
Opened 2023-02-08 23:49 UTC by michaelaeriksen

2023-05-16 20:07 UTC, ahatstat commented
This would be helpful to have.  Is there a plan to merge this PR?

2023-07-14 07:17 UTC, fmauch requested changes
Thank you for the contribution @michaelaeriksen!

I like the idea in general. There are a couple of docstrings missing and a couple of changes seem not necessarily be connected to the actual PR topic, please see my comments.

2023-07-14 07:17 UTC, fmauch commented on CMakeLists.txt
> +target_compile_options(urcl PRIVATE ${CXX17_FLAG})
What was your motivation for that switch? In my point of view it does make sense to export this to downstream packages.

A better approach would be to expose [`target_compile_features`](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards) but I don't really see this relevant in the scope of this PR.

2023-07-14 07:17 UTC, fmauch commented on include/ur_client_library/comm/tcp_socket.h
> +  std::chrono::milliseconds reconnection_time_;
Why has this been changed to milliseconds?

2023-07-14 07:17 UTC, fmauch commented on include/ur_client_library/comm/producer.h
> +  void setupProducer(size_t max_num_tries = 0, std::chrono::milliseconds reconnection_time = std::chrono::seconds(10)) override
We try to document **all** parameters to public methods.

2023-07-14 07:17 UTC, fmauch commented on include/ur_client_library/comm/pipeline.h
> +  virtual void setupProducer(size_t max_num_tries = 0, std::chrono::milliseconds reconnection_time = std::chrono::seconds(10))
We try to document **all** parameters to public methods.

2023-07-14 07:17 UTC, fmauch commented on include/ur_client_library/comm/pipeline.h
> +  void init(size_t max_num_tries = 0, std::chrono::milliseconds reconnection_time = std::chrono::seconds(10))
We try to document **all** parameters to public methods.

2023-07-14 07:17 UTC, fmauch commented on include/ur_client_library/ur/dashboard_client.h
> +  bool connect(size_t max_num_tries = 0, std::chrono::milliseconds reconnection_time = std::chrono::seconds(10));
We try to document **all** parameters to public methods.

2023-08-29 13:31 UTC, closed without merging