Added RTDEClient constructor with vector recipes
UniversalRobots/Universal_Robots_Client_Library pull request #143
Opened 2023-03-14 13:19 UTC by dagare

2023-03-21 13:18 UTC, dagare commented
I will make a new addition to this PR

2023-07-08 17:44 UTC, fmauch reviewed
@dagare Thank you for the contribution. Could you please provide some insight why you see this as beneficial?

I'm considering to suggest only allow passing recipes to the `RTDEClient` class as vectors directly, so parsing a file (if any) would have to be done a level higher up.

@RobertWilbrandt what do you think?

2023-08-01 10:08 UTC, urrsk commented
I will suggest we add the support first.
When we can consider to deprecate the file dependent constructor later

2023-08-10 13:59 UTC, urmahp reviewed
Thank you @dagare for the contribution. 

I have added a small adjustment, but other than that it looks good.

2023-08-10 13:59 UTC, urmahp commented on src/rtde/rtde_client.cpp
> +  , pipeline_(prod_, PIPELINE_NAME, notifier)
I think that producer_fifo_scheduling should be set to true, such that it looks identical to the original constructor. 
```suggestion
  , pipeline_(prod_, PIPELINE_NAME, notifier, true)
```

2023-08-23 08:38 UTC, urmahp commented
Before merging I suggest that we add checks in the constructor to see if the recipes are empty and whether "timestamp" is part of the output_recipe.

2023-08-29 07:55 UTC, urrsk requested changes

2023-08-29 07:55 UTC, urrsk commented on include/ur_client_library/rtde/rtde_client.h
> +   * \param input_recipe_file Vector containing the input recipe
Should fix the CI error as well

2023-08-29 09:02 UTC, urmahp commented
Thank you for the contribution @dagare.

2023-08-29 09:04 UTC, merged