Added check to ensure that the targets are reachable within the robot…
UniversalRobots/Universal_Robots_Client_Library pull request #184
Opened 2023-09-26 10:29 UTC by urmahp

…s limits

This will break the test_joint_trajectory_position_interface test in the ROS Driver as part of the test is designed to activate the speed scaling by sending unreachable targets. These changes therefore require that we update the test in the ROS Driver.

2024-06-10 09:14 UTC, fmauch commented on resources/external_control.urscript
> +        q_act = get_actual_joint_positions()
```suggestion
```

2024-06-10 09:14 UTC, fmauch commented on resources/external_control.urscript
> +        q_act = get_actual_joint_positions()
```suggestion
```

2024-06-10 09:14 UTC, fmauch commented on resources/external_control.urscript
> +        terminateProgram()
I wonder what would be the benefit of actually quitting here? We could instead just ignore the command.

2024-06-10 12:42 UTC, fmauch commented
While this is in a state where everything seems to do its job as intended, it's actually not as simple as that. Since we use `servoj` for executing trajectories in the position-based case, there is some delay between the moment where we call servoj and servoj actually starting the motion. Thus, simply looking at the current positions and the ones coming in as new targets will not necessarily reflect the actual velocities. I'll try to add a test showing this.

2024-07-10 14:16 UTC, fmauch commented
I've updated this so that it doesn't terminate the program but instead ignores the commands as long as they are infeasible. With this, when I start this with a driver that always commands [0,0,0,0,0,0], the robot doesn't move until we send a target that is close to its current position.

I used a non-blocking popup as we discussed, but thinking about this, a blocking popup might actually be more feasible, don't you agree @urrsk ?

2024-07-12 22:08 UTC, urrsk requested changes

2024-07-12 22:08 UTC, urrsk commented on resources/external_control.urscript
> +      last_violation_popup_counter = last_violation_popup_counter + 1
```suggestion
      if last_violation_popup_counter == 0:
        # Keep making a popup as long as the targets are too much off
        local str = str_cat(str_cat("Velocity ", velocity), str_cat(str_cat(" required to reach the received target ", step_end), str_cat(str_cat(" within ", time), " seconds is exceeding the joint velocity limits. Ignoring commands until a valid command is received.")))
        textmsg(str)
        popup(str, error=True, blocking=False)
      end
      # Report the error every 5 sec
      last_violation_popup_counter = last_violation_popup_counter + 1
      if last_violation_popup_counter * get_steptime() >= 5.0:
        last_violation_popup_counter = 0
      end
```
I think it is fine it is not blocking, as the alterative is more to terminating the program instead. Though let's ensure that the popup keeps coming if a continues stream of invalid targets keeps coming

2024-07-16 09:41 UTC, fmauch commented
@urrsk Now everything is where I think I would like it to be and the tests are in line, as well. If you could take another look, that would be awesome. Or @VinDp.

2024-07-16 10:48 UTC, urrsk requested changes

2024-07-16 10:48 UTC, urrsk commented on resources/external_control.urscript
> +  if time <= 0.0:
I am afraid that some people are putting the robot's current position as the first node in the trajectory.
Maybe we could ignore this not with the time of zero if:
1. it is the first node in the path
1. it is very close to the robot's current position

2024-07-16 10:48 UTC, urrsk commented on resources/external_control.urscript
> +  textmsg("Trajectory finished with result ", trajectory_result)
Maybe convert the trajectory_result to a readable string before sending it to the log

2024-07-18 11:34 UTC, fmauch commented
@urrsk I implemented the things discussed. I was a bit puzzled as I found out that when ignoring the first trajectory point, apparently the read-from-socket call times out. That's why I increased the timeout in this PR. However, that doesn't seem right to me. I checked that sending out the trajectory points only took a few microseconds in the test program, so the timeout could either result from

* The network delaying the package
* Delay between socket send command and package actually entering the network layer
* Socket read in the thread being at lower priority?

I quickly modified the `trajectoryThread()` in order to just print the points to a textmsg instead of executing them and that showed the same behavior. The first trajectory point was printed fine, the others timed out.

2024-07-18 16:32 UTC, urrsk commented
> @urrsk I implemented the things discussed. I was a bit puzzled as I found out that when ignoring the first trajectory point, apparently the read-from-socket call times out. That's why I increased the timeout in this PR. However, that doesn't seem right to me. I checked that sending out the trajectory points only took a few microseconds in the test program, so the timeout could either result from
> 
> * The network delaying the package
> * Delay between socket send command and package actually entering the network layer
> * Socket read in the thread being at lower priority?
> 
> I quickly modified the `trajectoryThread()` in order to just print the points to a textmsg instead of executing them and that showed the same behavior. The first trajectory point was printed fine, the others timed out.

Interesting, it seems we need to do a bit more investigation on this

2024-09-06 09:33 UTC, fmauch commented
@urrsk as discussed I use the higher timeout when the robot isn't moving, yet only. Could you please have another look?

2024-09-06 10:50 UTC, fmauch commented
I'll investigate why the noetic tests fail. A quick look didn't make it clear to me.

2024-09-09 13:36 UTC, fmauch requested changes

2024-09-09 13:36 UTC, fmauch commented on .github/workflows/industrial-ci.yml
> +          - {NAME: noetic, DOWNSTREAM_WORKSPACE: "github:fmauch/Universal_Robots_ROS_Driver#fix_trajectory_forward_test https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS_Driver/m
```suggestion
          - {NAME: noetic, DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS_Driver#master https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS_Driver/master/.noetic.rosinstall"}
```

2024-09-09 13:37 UTC, fmauch commented
> I'll investigate why the noetic tests fail. A quick look didn't make it clear to me.

Found it. The actual test wasn't working properly and this got uncovered by this PR. Necessary changes are being implemented in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/721

2024-09-10 07:48 UTC, fmauch approved these changes
Approving so my change-request block goes away.

2024-09-10 08:50 UTC, urrsk approved these changes
I have mainly focused on the script code in my review

2024-09-10 11:17 UTC, merged